// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

using System;

namespace Roslynator.CodeAnalysis.CSharp
{
    public static partial class DiagnosticIdentifiers
    {
        public const string UsePropertySyntaxNodeSpanStart = "ROS0001";
        public const string UsePropertySyntaxNodeRawKind = "ROS0002";
        public const string RedundantConditionalAccess = "ROS0003";
        public const string UsePatternMatching = "ROS0004";
    }
}